### ISSUE TITLE
FPGA_VHDL_code_and_data/src

### ISSUE THREAD

**Issue by LFBanez** [AdrianAlcolea/FPGA_accelerator_for_GBDT#1]
Hello,
Good day.

Trying to replicate this project/research. Under path: FPGA_VHDL_code_and_data/src, the Hard Disk image files cannot be mounted. Is it possible you could share the raw file same on the path: FPGA_VHDL_code_and_data/sim?

It would be a great help.
![image](https://github.com/user-attachments/assets/1fdee695-3f99-4727-80c2-d436ff682a6e)

Thank you.

**Comment by AdrianAlcolea** [comment]
Hello, I saw you closed it... did you achieved to replicate it?
